### ISSUE TITLE
simple function triggers an unexpected dimension mismatch error

### ISSUE THREAD

**Issue by Roger-luo** [FluxML/Mjolnir.jl#25]
MWE:

```jl
using Mjolnir, IRTools

function foo()
    for i in 2:3
        2 + 3
    end
    return
end

ir = @code_ir foo()
Mjolnir.return_type(ir)
```

I think this should return `Nothing` or at least trigger the iterate error in #7 but this gives me

```
ERROR: DimensionMismatch("array could not be broadcast to match destination")
```

on current master.

**Comment by femtomc** [comment]
@Roger-luo You have to pass in the arg types to `return_type`.

E.g.

`Mjolnir.return_type(ir, Tuple{})`

this still breaks because of the `iterate` call.

**Comment by Roger-luo** [comment]
Ah I see. Thanks!
