### ISSUE TITLE
Ambiguous meaning of @trace f(Int)

### ISSUE THREAD

**Issue by MasonProtter** [FluxML/Mjolnir.jl#9]
Current, it seems that `@trace f(Int)` means the same thing as `@trace f(x::Int)`, but that seems to be kind of ambiguous. What if I meant for `f(T)` to be a function that takes in a type (in this case, `Int`) and I wanted to trace `f` with `Int` as a `Const`?

**Comment by MikeInnes** [comment]
You can get the type-itself behaviour with `Type{T}` or `Const(T)`.

But note that `@trace` is really only meant as a convenience for the repl (the common case being things like `pow(2, Int)` where this behaviour is useful). Outside of that you probably want the `trace` function, which consistently takes only types.

**Comment by MasonProtter** [comment]
Makes sense.

**Comment by MasonProtter** [comment]
Just a thought, but I discovered today that this is possible: https://github.com/JuliaLang/julia/issues/33784#issuecomment-645598787

so we could have the syntax `@trace f(::Int)` rather than `@trace f(Int)`.

**Comment by MikeInnes** [comment]
I think I tried something like this an ran into an issue for some reason, but I can't remember what. As long as it parses right it seems sensible to try it, though.

**Comment by MasonProtter** [comment]
> I think I tried something like this an ran into an issue for some reason, but I can't remember what. 

Fair enough. I'll try opening a PR in the next few days and we'll see if I can rediscover any issues.
